services:
  mc:
    image: itzg/minecraft-server
    container_name: minecraft-technical-smp
    tty: true
    stdin_open: true
    restart: unless-stopped

    ports:
      - "25565:25565"
      - "19132:19132/udp"

    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "LATEST"
      MEMORY: "8G"

      USE_AIKAR_FLAGS: "true"

      ENABLE_AUTOPAUSE: "true"
      AUTOPAUSE_TIMEOUT_EST: 600

      FIX_OWNERSHIP: "true"

      PLUGINS: |
        https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
        https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot

      MODRINTH_PROJECTS: "viaversion,drivebackupv2"

    volumes:
      - mc-data:/data

      # ---- GITOPS CONFIG MOUNTS ----
      - ./config/server.properties:/data/server.properties
      - ./config/spigot.yml:/data/spigot.yml
      - ./config/paper-global.yml:/data/config/paper-global.yml
      - ./config/paper-world-defaults.yml:/data/config/paper-world-defaults.yml

volumes:
  mc-data:
