services:
  mc:
    image: itzg/minecraft-server
    container_name: minecraft-technical-smp
    tty: true
    stdin_open: true
    restart: unless-stopped

    ports:
      - "25565:25565"
      - "19132:19132/udp"
      - "25575:25575"
      - "8080:8080"

    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "LATEST"
      MEMORY: "8G"

      USE_AIKAR_FLAGS: "true"

      ENABLE_AUTOPAUSE: "false"
      # AUTOPAUSE_TIMEOUT_EST: 600

      FIX_OWNERSHIP: "true"

      PLUGINS: |
        https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
        https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
        https://hangarcdn.papermc.io/plugins/Kyle/Otherside/versions/1.1/PAPER/otherside-1.1.jar

      MODRINTH_PROJECTS: "viaversion, viabackwards, drivebackupv2, squaremap, chunky, tab-was-taken, placeholderapi, head-drop, gravesx"

      PAPI_DOWNLOAD_EXPANSIONS: "Player"

      # Copy custom configs from /config to /data on startup
      COPY_CONFIG_DEST: /data

      # Server.properties configuration via environment variables
      DIFFICULTY: "normal"
      MODE: "survival"
      MOTD: "itzmaniss Minecraft Server"
      MAX_PLAYERS: 20
      VIEW_DISTANCE: 16
      SIMULATION_DISTANCE: 12
      ALLOW_FLIGHT: "false"
      ONLINE_MODE: "true"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "password"
      RCON_PORT: 25575
      SPAWN_PROTECTION: 16
      MAX_WORLD_SIZE: 29999984
      GENERATE_STRUCTURES: "true"
      LEVEL_TYPE: "minecraft:normal"
      HARDCORE: "false"
      FORCE_GAMEMODE: "false"
      GAMEMODE: "survival"

    volumes:
      - ${MC_DATA_PATH}:/data
      # ---- GITOPS CONFIG MOUNT ----
      # Mount entire config directory - files will be copied to /data on startup
      - ./config:/config:ro
